- name: Deploy to Kubernetes
  hosts: local
  vars:
    dockerhub_user: "{{ dockerhub_user }}"
    aws_access_key_id: "{{ aws_access_key_id }}"
    aws_secret_access_key: "{{ aws_secret_access_key }}"
    aws_region: "{{ aws_region }}"
    s3_bucket_name: "{{ s3_bucket_name }}"
  tasks:
    - name: Download kubectl
      get_url:
        url: "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Install kubectl
      ansible.builtin.package:
        name: kubectl
        state: present

    - name: Create Kubernetes manifests
      template:
        src: k8s/deployment.yml.j2
        dest: ./deployment.yml
      with_items:
        - clickstackbackend
        - clickstackfrontend
        - clickstack_db

    - name: Apply Kubernetes manifests
      command: kubectl apply -f ./deployment.yml
