- name: Deploy to Kubernetes
  hosts: local
  vars:
    dockerhub_user: "{{ dockerhub_user }}"
    aws_access_key_id: "{{ aws_access_key_id }}"
    aws_secret_access_key: "{{ aws_secret_access_key }}"
    aws_region: "{{ aws_region }}"
    s3_bucket_name: "{{ s3_bucket_name }}"
  tasks:
    - name: Get latest kubectl version
      command: curl -L -s https://dl.k8s.io/release/stable.txt
      register: kubectl_version

    - name: Set kubectl download URL
      set_fact:
        kubectl_url: "https://dl.k8s.io/release/{{ kubectl_version.stdout }}/bin/linux/amd64/kubectl"

    - name: Download kubectl
      get_url:
        url: "{{ kubectl_url }}"
        dest: /usr/local/bin/kubectl
        mode: '0755'
      when: ansible_os_family == 'Linux'

    - name: Install Kubernetes Ansible modules
      ansible.builtin.pip:
        name: kubernetes

    - name: Create Kubernetes manifests
      template:
        src: k8s/deployment.yml.j2
        dest: ./deployment.yml
      with_items:
        - clickstackbackend
        - clickstackfrontend
        - clickstack_db

    - name: Apply Kubernetes manifests
      command: kubectl apply -f ./deployment.yml
