- name: Deploy to Kubernetes
  hosts: local
  vars:
    dockerhub_user: "{{ dockerhub_user }}"
    aws_access_key_id: "{{ aws_access_key_id }}"
    aws_secret_access_key: "{{ aws_secret_access_key }}"
    aws_region: "{{ aws_region }}"
    s3_bucket_name: "{{ s3_bucket_name }}"
  tasks:
    - name: Install Minikube on Linux
      block:
        - name: Download Minikube binary
          get_url:
            url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
            dest: /usr/local/bin/minikube
            mode: '0755'
          when: ansible_os_family == 'Linux'

        - name: Start Minikube
          command: minikube start
          when: ansible_os_family == 'Linux'

    - name: Ensure kubectl is using Minikube context
      command: kubectl config use-context minikube    

    - name: Install Kubernetes Ansible modules
      ansible.builtin.pip:
        name: kubernetes

    - name: Create Kubernetes manifests
      template:
        src: k8s/deployment.yml.j2
        dest: ./deployment.yml
      with_items:
        - clickstackbackend
        - clickstackfrontend
        - clickstack_db

    - name: Apply Kubernetes manifests
      command: kubectl apply -f ./deployment.yml --validate=false
